
services:
  app:
    container_name: my_fast_api_d_c
    build: .
    external_links:
      - my_pg_db_d_c:my_pg_db_d_c
    ports:
      - "8008:8000"
    depends_on:
      - db
      - redis
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    restart: always
    environment:
      - API_REDIS_HOST=redis
    env_file:
      - .env
  db:
    image: postgres:12.0-alpine
    container_name: my_pg_db_d_c
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fast_api
    restart: always
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - 'rabbitmq_data:/data'
  redis:
    container_name: redis
    build:
      context: .
      dockerfile: redis/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  rabbitmq_data: